# Uncomment the next line to define a global platform for your project
source 'git@gitee.com:libolinios/LBLSpecs.git'
platform :ios, '9.0'

target 'DownloadMediator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'DownloadLib'

  

end
